### ISSUE TITLE
Плащ невидимка для гма

### ISSUE THREAD

**Issue by ArtiomLiakh** [HomelessMage/Zvezda-Bundle#11]
Прозрачная одежда с максимальными стами защиты скрывающая ник персонажа.
(Возможно) добавление отдельного скрытого job гма в невидимке для спавна после старта?

**Comment by HomelessMage** [comment]
Зачем?

**Comment by ArtiomLiakh** [comment]
Не всё можно сделать из спектратора.
Заложить бомбу. Положить предмет в конкретный контейнер, будь то сумка или шкаф. Иногда нужно починить конкретную стену пока игроки тупят или проверить что где лежит. Есть необходимость объяснять спец ролям голосом из невидимки их задачу, что выглядит очень комично когда появившийся из воздуха санитар объясняет пахану что делать.  Речь про возможность переключения из спектратора на невидимую куклу стоящую в обычное время в АФК где то в коридоре. А ну и ещё потому что Тигран жаловался что он видит как я телепортируюсь по станции.
