### ISSUE TITLE
Наименование коммитов

### ISSUE THREAD

**Issue by HomelessMage** [HomelessMage/Zvezda-Bundle#19]
Для того чтобы быстро находить ошибки и исправлять их, нужно писать в описании коммита какой именно предмет добавлен/изменён/удалён.

@ArtiomLiakh 
@PuchaBro

![image](https://user-images.githubusercontent.com/42868046/173692505-a4ae364b-19d1-4d9d-89de-3dff1ae93d99.png)

**Comment by HomelessMage** [comment]
Отпишитесь как прочитаете.

**Comment by ArtiomLiakh** [comment]
lol didn't read

**Comment by HomelessMage** [comment]
@PuchaBro

**Comment by HomelessMage** [comment]
@PuchaBro жду ответа

**Comment by PuchaBro** [comment]
да понял
