### ISSUE TITLE
Локализация идентификаторов

### ISSUE THREAD

**Issue by HomelessMage** [HomelessMage/Zvezda-Bundle#2]
При попытке спавна объекта если протаббить его название в файле локализации (он обнаруживается в консоли) он не спавнится, со следующей ошибкой:
```
entityname not found
```

**Comment by HomelessMage** [comment]
Возможное решение:
продублировать все входы идентификаторов объектов в файле локализации

https://discord.com/channels/103209684680323072/426913209602146315/1085596871524892814
```
For anyone who's curious, I found a workaround to the problem of being unable to properly override tooltips because overriding localization files only kind of works
Because it was seemingly picking at random between my modded description and the vanilla one, I tried duplicating the modded description, and to my surprise, it actually reduced the chances of the vanilla one appearing
there are now 40 or so entries of the exact same description in my mod files, which gives the vanilla description a ~2.5% chance of appearing
an imperfect and jank solution but one that functionally works to overwrite otherwise un-overridable files
```
![image](https://user-images.githubusercontent.com/42868046/226059012-afecf0a1-4d52-43e6-83e6-b3ccc48fd2e1.png)

**Comment by HomelessMage** [comment]
Коммит с entries https://github.com/HomelessMage/Zvezda-Bundle/commit/60716be9fe0d9a309ee57462f54021eb29a51dd8

**Comment by PuchaBro** [comment]
Возможное решение:
нужно всем предметам приписать name="".
На примере Лихорадки
 <AfflictionHusk name="Лихорадка" identifier="necroinfection" description="Кажется, ты не можешь ясно мыслить. У тебя продолжают быть видения того, как ты потворствуешь разрыванию и разрыванию своей собственной плоти." type="alieninfection" targets="human" huskedspeciesname="slasher" causeofdeathdescription="Succumbed to necromorph infection." selfcauseofdeathdescription="Вы были захвачены паразитом-некроморфом." limbspecific="false" indicatorlimb="Torso" activationthreshold="0" showiconthreshold="40" karmachangeonapplied="-1" maxstrength="100" achievementonremoved="healhusk" iconcolors="255,0,0,255;255,0,0,255;255,0,0,255">

**Comment by PuchaBro** [comment]
Я так понял это типо 2 айди предмета, можешь зайти и сам проверить впринципе

**Comment by HomelessMage** [comment]
Ты не понял. Вот ты написал что если атрибут name в тэге предмета поставить то он будет работать в консоли?

**Comment by PuchaBro** [comment]
Хорошо хозяин

**Comment by HomelessMage** [comment]
@PuchaBro доделал?

**Comment by HomelessMage** [comment]
Исправлено в https://github.com/HomelessMage/Zvezda-Bundle/commit/ffb6bc023002b5c19dd96fe458f99ec5892741b9

**Comment by PuchaBro** [comment]
хорошо начальник только не ругайся

**Comment by ArtiomLiakh** [comment]
Нахрюк будет взят в обработку

**Comment by HomelessMage** [comment]
Не трогайте ничего. Кто-то из вас разъебал идентификаторы.

**Comment by HomelessMage** [comment]
Исправлено в https://github.com/HomelessMage/Zvezda-Bundle/commit/f1c463f82e5a76a7035a1c2b2f42e95f57011564
