### ISSUE TITLE
Неправильные названия директорий и файлов

### ISSUE THREAD

**Issue by HomelessMage** [HomelessMage/Zvezda-Bundle#23]
1. @ArtiomLiakh, нужно исключить названия, не соответствующие правильным аналогам на английском языке, поскольку осуществлять навигацию с данными наименованиями в будущем станет сложно: не [Ebaki](https://github.com/HomelessMage/Zvezda-Bundle/tree/dev/Creatures/Ebaki) а `DeadSpaceMonsters` или что-то подобное, не [Torgomat](https://github.com/HomelessMage/Zvezda-Bundle/tree/dev/Map/Torgomat), а `VendingMachine` или что-то подобное
3. Исключить орфографические ошибки из наименований, файлы с ошибками в названиях будет создавать проблемы при навигации: не [Solders](https://github.com/HomelessMage/Zvezda-Bundle/tree/dev/Items/Jobgear/Military/Solders) а `Soldiers`
5. @PuchaBro, непонятна логика именований директории: [As_vall](https://github.com/HomelessMage/Zvezda-Bundle/tree/dev/Items/Weapons/Weapon/As_vall)
Если нужно сделать директорию с огнестрельным оружием, то можно сделать что-то вроде:
`Items/Weapons/Firearms`

Придерживайтесь правила наименований файлов и директорий в соответствии со стандартом [camelcase](https://ru.wikipedia.org/wiki/CamelCase).
Это упростит работу и мне, и вам.

Отпишитесь как прочитаете.

**Comment by PuchaBro** [comment]
хорошо

**Comment by HomelessMage** [comment]
Туда же: [xolod](https://github.com/HomelessMage/Zvezda-Bundle/tree/dev/Systems/Temperature) какой-то

**Comment by ArtiomLiakh** [comment]
Это ты ещё холод и керку не видел 
Ебаки это общая папка для всех агрессивных игроку монстров из модов 
Да, пока что она пуста 
Торгомат назыаается торгоматом для идентификации потому что vending machine в сумме 3 штуки

**Comment by HomelessMage** [comment]
Постарайтесь исправить это.
