### ISSUE TITLE
Дубликаты файлов

### ISSUE THREAD

**Issue by HomelessMage** [HomelessMage/Zvezda-Bundle#5]
```
Items\Weapons\Weapon\weapons.xml
Items\Weapons\Import\weapons.xml
```
Что это и нахуя оно?

**Comment by HomelessMage** [comment]
Кто это сделал отпишись и исправь это, файлы дублированы

**Comment by HomelessMage** [comment]
Зачем в двух файлах объявляется один и тот же идентификатор?
![image](https://user-images.githubusercontent.com/42868046/226593339-ce0b5c29-93ae-4528-8915-30cea717b69e.png)
![image](https://user-images.githubusercontent.com/42868046/226593446-e91ee3d7-2433-4e8c-bee4-fd96a8b467a7.png)

**Comment by HomelessMage** [comment]
@ArtiomLiakh это ты делал, исправляй эту хуйню

**Comment by ArtiomLiakh** [comment]
> Зачем в двух файлах объявляется один и тот же идентификатор? ![image](https://user-images.githubusercontent.com/42868046/226593339-ce0b5c29-93ae-4528-8915-30cea717b69e.png) ![image](https://user-images.githubusercontent.com/42868046/226593446-e91ee3d7-2433-4e8c-bee4-fd96a8b467a7.png)

Один файл тестовый второй рабочий, исправлю вместе с обновлением шахтёрской системы
