### ISSUE TITLE
Калаши за 1 рожок уничтожают 3 двери

### ISSUE THREAD

**Issue by ArtiomLiakh** [HomelessMage/Zvezda-Bundle#6]
Урон по двери с автомата разрушает двери, но не стены.

**Comment by HomelessMage** [comment]
Это стеклянные двери только. Проверь те что без стекла.

**Comment by ArtiomLiakh** [comment]
![image](https://user-images.githubusercontent.com/70390197/226949535-17609223-10d9-4025-b971-1b0e05a34b86.png)

**Comment by HomelessMage** [comment]
Предположительно исправил в https://github.com/HomelessMage/Zvezda-Bundle/commit/a3f568810c7c6467a63da333c7f5562f0eeb9888
