### ISSUE TITLE
Генерация имен и персонажей

### ISSUE THREAD

**Issue by HomelessMage** [HomelessMage/Zvezda-Bundle#62]
Изменить фамилии генерации персонажей на гендерно-нейтральные

**Comment by HomelessMage** [comment]
Отбой! Не убирать имена, а сделать гендерно-нейтральные фамилии!
Чтобы не было "Аглая Александов"

**Comment by HomelessMage** [comment]
По типу: Не "Комаров" или "Комарова", а "Комаренко"

**Comment by HomelessMage** [comment]
Чтобы у всех ИИ были адекватные имена

**Comment by ArtiomLiakh** [comment]
Вырезать женщин

**Comment by HomelessMage** [comment]
https://ru.wiktionary.org/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F:%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5_%D1%84%D0%B0%D0%BC%D0%B8%D0%BB%D0%B8%D0%B8/ru
[![image](https://user-images.githubusercontent.com/42868046/180654713-e15f090c-4035-4378-a703-52737120e582.png)](https://ru.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D1%84%D0%B0%D0%BC%D0%B8%D0%BB%D0%B8%D1%8F)

**Comment by HomelessMage** [comment]
@ArtiomLiakh ссылку на коммит с изменением фамилий

**Comment by HomelessMage** [comment]
Пока не будет исправлено пулл реквеста не будет

**Comment by ArtiomLiakh** [comment]
https://github.com/HomelessMage/Zvezda-Bundle/commit/b1f273d16cb4d895f9f6a21072f5fca1851ec1f3
