### ISSUE TITLE
Найти способ давать урон персонажу держащему раскалённый метал

### ISSUE THREAD

**Issue by ArtiomLiakh** [HomelessMage/Zvezda-Bundle#72]
![image](https://user-images.githubusercontent.com/70390197/181515674-5cb2a030-9004-4e9e-b1c2-54b47bbd2342.png)

**Comment by HomelessMage** [comment]
```xml
<StatusEffect type="OnNotContained" target="Character">
        <Affliction identifier="burn" amount="1" />
</StatusEffect>
```

**Comment by HomelessMage** [comment]
Или `OnPicked`

**Comment by ArtiomLiakh** [comment]
OnNotContained не работает потому что предмет содержится в руке
OnPicked не работает потому что взять металл из контейнера не считается за поднятие предмета

**Comment by HomelessMage** [comment]
`OnActive`

**Comment by ArtiomLiakh** [comment]
https://github.com/HomelessMage/Zvezda-Bundle/commit/cc0c2d5414adf7bae9b02e6135a93927dedfe44f
